# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wiLLDt8z8Tc7bxgL98-YScOC26kAT8YO
"""

numbers = [12, 45, 23, 45, 67, 12]

largest = second_largest = float('-inf')

for num in numbers:
    if num > largest:
        second_largest = largest
        largest = num
    elif largest > num > second_largest:
        second_largest = num

if second_largest == float('-inf'):
    print("No second largest unique element found.")
else:
    print("Second largest element:", second_largest)