# -*- coding: utf-8 -*-
"""dupelements

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10YtRuqTrlOupmKlhBbkas8lCOAkt5oFR
"""

lst = [10, 20, 10, 30, 20, 40, 50, 40]
unique_list = []
for item in lst:
    if item not in unique_list:
        unique_list.append(item)

print("Original List:", lst)
print("List after removing duplicates:", unique_list)