# -*- coding: utf-8 -*-
"""pythonassignment1.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wiLLDt8z8Tc7bxgL98-YScOC26kAT8YO
"""
# Question1


numbers = [12, 45, 23, 45, 67, 12]

largest = second_largest = float('-inf')

for num in numbers:
    if num > largest:
        second_largest = largest
        largest = num
    elif largest > num > second_largest:
        second_largest = num

if second_largest == float('-inf'):
    print("No second largest unique element found.")
else:
    print("Second largest element:", second_largest)



#Question2

list = [12,19,10,23,12,19,1,10,1]
f= {}
for num in list:
    if num in f:
        f[num] +=1
    else:
        f[num] = 1
print("frequency=",f)
