# -*- coding: utf-8 -*-
"""rotate

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10YtRuqTrlOupmKlhBbkas8lCOAkt5oFR
"""

lst = [10, 20, 30, 40, 50]
k = 2


k = k % len(lst)


rotated = lst[-k:] + lst[:-k]

print("Original List:", lst)
print("Rotated List:", rotated)